name: roshetta_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Core
  get: ^4.6.5
  shared_preferences: ^2.0.17
  http: ^0.13.5
  dartz: ^0.10.1
  jwt_decoder: ^2.0.1
  # UI
  curved_labeled_navigation_bar: ^2.0.2
  otp_text_field: ^1.1.3
  # Media
  image_picker: ^0.8.6+1
  flutter_svg: ^2.0.1
  cached_network_image: ^3.2.3
  cached_video_player: ^2.0.4
  # Icons
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.4.0
  lottie: ^2.2.0
  # Date
  intl: ^0.17.0
  time_range_picker: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/imgs/
    - assets/lottie/
    - assets/json/
    - assets/videos/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-Bold.ttf
        - asset: assets/fonts/cairo/Cairo-ExtraBold.ttf
        - asset: assets/fonts/cairo/Cairo-Light.ttf
        - asset: assets/fonts/cairo/Cairo-Medium.ttf
        - asset: assets/fonts/cairo/Cairo-Regular.ttf
        - asset: assets/fonts/cairo/Cairo-SemiBold.ttf
